# Generated by Django 4.2.7 on 2025-10-20 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogininfo',
            old_name='username',
            new_name='user',
        ),
    ]
