# Generated by Django 4.2.7 on 2025-09-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='letterserialno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.EmailField(max_length=254, unique=True)),
                ('issuername', models.CharField(max_length=50)),
                ('issuedto', models.CharField(max_length=80)),
                ('subject', models.CharField(blank=True, max_length=30)),
                ('issuedate', models.DateField()),
            ],
        ),
    ]
