# Generated by Django 4.2.7 on 2025-10-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('issuername', models.CharField(blank=True, max_length=50, null=True)),
                ('issuedto', models.CharField(blank=True, max_length=80, null=True)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('issuedate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='letterserialno',
        ),
    ]
