# Generated by Django 4.2.7 on 2025-09-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_letterserialno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterserialno',
            name='issuedate',
            field=models.DateField(blank=True),
        ),
    ]
