# Generated by Django 4.2.7 on 2025-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('Amount', models.CharField(max_length=80)),
            ],
        ),
    ]
