# Generated by Django 4.2.7 on 2025-09-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_letterserialno_issuedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterserialno',
            name='serialno',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
