# Generated by Django 4.2.7 on 2025-09-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_letterserialno_serialno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterserialno',
            name='issuedto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='letterserialno',
            name='issuername',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
