# Generated by Django 4.2.7 on 2025-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_letterserialno_issuedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterserialno',
            name='issuedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letterserialno',
            name='issuedto',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='letterserialno',
            name='issuername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letterserialno',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
